In [24]:
import numpy as np

a = numpy.random.randint(1, 10, (2, 3))
b = np.random.randint(1, 10, (2, 3))

print(a)
print(b)
print( '-' *10)

print(a+b)
print('-' * 10)

print(a-b)
print('-' * 10)

print(a*b)
print('-' * 10)

print(a / b)
print('-' * 10)

print(a * 5)
print('-' * 10)

print(a > b)

[[7 8 6]
 [8 1 5]]
[[3 8 5]
 [1 1 3]]
----------
[[10 16 11]
 [ 9  2  8]]
----------
[[4 0 1]
 [7 0 2]]
----------
[[21 64 30]
 [ 8  1 15]]
----------
[[2.33333333 1.         1.2       ]
 [8.         1.         1.66666667]]
----------
[[35 40 30]
 [40  5 25]]
----------
[[ True False  True]
 [ True False  True]]


In [11]:
arr = np.array(['ba','ch','ap'])

print(np.sort(arr)) #정렬

['ap' 'ba' 'ch']


In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

print(arr)
print('-' * 20)

print(arr.mean())  #평균
print(arr.sum()) #더하기
print(arr.std()) #편차
print(arr.var())
print(arr.min()) #최소값
print(arr.max()) #최대값

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
--------------------
9.5
171
5.188127472091127
26.916666666666668
1
18


In [19]:
# sqrt 제곱근 exp지수함수

arr = np.arange(10)

print(arr)

print(np.sqrt(arr))
print(np.exp(arr))

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [23]:
a = np.random.randint(0, 10, (2, 3))
print(a)
np.savetxt("./data/score.csv", a)                     

[[3 7 7]
 [1 5 2]]
